url: "https://dani-co-cn.github.io/daniel-julia" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "." # the subpath of your site, e.g. /blog
title: "Salzzitronen" # the name of your site, e.g. ACME Corp.
